[[pages]]
path = "src/main.py"
name = "–ì–ª–∞–≤–Ω–∞—è"
icon = "üè†"

[[pages]]
name = "–ò–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è"
icon = "üåÑ"
is_section = true

[[pages]]
path = "src/pages/visualization.py"
name = "–í–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—è –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–π"
icon = "üñºÔ∏è"

[[pages]]
path = "src/pages/xray_image_visualization.py"
name = "–í–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—è —Ä–µ–Ω—Ç–≥–µ–Ω–æ–≤—Å–∫–∏—Ö –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–π"
icon = "ü©ª"

[[pages]]
path = "src/pages/increase_size.py"
name = "–ò–∑–º–µ–Ω–µ–Ω–∏–µ —Ä–∞–∑–º–µ—Ä–æ–≤ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–π"
icon = "üßê"